# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.blacklistedKernelModules = lib.mkDefault [ "radeon" "amdgpu" ];
  services.xserver.videoDrivers = lib.mkDefault [ "intel" ];


  fileSystems."/" =
    { device = "/dev/mapper/nixos-enc";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."nixos-enc".device = "/dev/disk/by-uuid/70e13c82-b758-4266-a894-76c5a1bb8ace";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6009-86AA";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}